### ISSUE TITLE
Published version broken since 2.0.3

### ISSUE THREAD

**Issue by orinem** [open-amt-cloud-toolkit/ui-toolkit-react#390]
What should be the "dist" folder in @open-amt-cloud-toolkit/ui-toolkit-react 2.0.3 and 2.0.4 is actually a plain file containing the contents of package.json.

This is presumably from the following:

```
"scripts": {
    "prepublishOnly": "cp package.json dist",
```
in package.json which was introduced in 2.0.3.

It should ensure the dist folder exists before copying package.json into it.

**Comment by rsdmike** [comment]
Hey @orinem , our CI/CD typically takes care of building first before trying to publish which essential lymakes sure the dist dir exist. That said,  i've gone ahead and updated the package.json if you'd like to take a look.

**Comment by orinem** [comment]
PR looks OK to me.
